NoelPlus/urls.py
#NoelPlus-urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('zone.urls')),
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('chat/',include('chat.urls')),
    path('blog/',include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.THUMBNAIL_URL, document_root=settings.THUMBNAIL_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
#blog-urls
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:blog_id>/', views.blog, name='blog'),
    #path('<int:blog_id>/like/', views.ike, name='like'),
    path('<int:post_id>/edit/', view=views.edit, name='edit'),
    path('<int:blog_id>/comment/', view=views.comment, name='comment'),
    path('new/', view=views.new, name='new'),
]

gpt/urls.py
from django.urls import path
from . import views

app_name = 'gpt'

urlpatterns = [
    path('', views.gpt, name='gpt'),
]

noel-refactored/urls.py
#noel-refactored-urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('index.urls')),
    path('zone/',include('zone.urls')),
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('chat/',include('chat.urls')),
    path('blog/',include('blog.urls')),
    path('gpt/',include('gpt.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.THUMBNAIL_URL, document_root=settings.THUMBNAIL_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
#blog-models
from django.db import models
from django.conf import settings

class Blog(models.Model):
    content = models.TextField(verbose_name='博文内容')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='作者')
    pub_time = models.DateTimeField('发布日期')
    pinned = models.BooleanField('是否顶置', default=False)

class Like(models.Model):
    post = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name='所属博客')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='点赞者', related_name='博客点赞者')

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name='所属博客')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='评论者', related_name='博客评论者')
    content = models.CharField('评论内容', max_length=1000)
    pub_time = models.DateTimeField('发布时间')
    reply = models.IntegerField('Reply index', default=-1)

blog/views.py
from django import template
from django.shortcuts import render, redirect
from django.http import *
from django.contrib.auth.decorators import login_required
from datetime import datetime
import markdown

from .models import *


class HttpResponseImATeaPot(HttpResponse):
    status_code = 418

def mdconv(text: str):
    md = markdown.Markdown(
        extensions=[
            'markdown.extensions.codehilite',
            'markdown.extensions.meta',
            'markdown.extensions.extra',
            'pymdownx.arithmatex'
        ],
        extension_configs={
            'pymdownx.arithmatex': {
                'generic': True
            }
        }
    )
    res = md.convert(text)
    meta = md.Meta
    for i in meta:
        if len(meta[i]) == 1:
            meta[i] = meta[i][0]
    return (res, md.Meta)


#博客选择页面
@login_required(login_url='user:login')
def index(request):
    blogs = Blog.objects.all().order_by('-pinned','-pub_time')
    if len(blogs) > 30:
        blogs = blogs[:30]
    
    for blog in blogs:
        blog.comment_count = Comment.objects.filter(blog=blog).count()
        blog.formatted, blog.meta = mdconv(blog.content)
    
    context = {
        "user": request.user,
        "blogs": blogs
    }
    return render(request, 'blog/index.html', context)

#博客详情页
@login_required(login_url='user:login')
def blog(request, blog_id):
    blog = Blog.objects.get(id=blog_id) 
    comments = Comment.objects.filter(blog=blog)
    blog.formatted, blog.meta = mdconv(blog.content)
    context = {
        'editable': request.user == blog.author,
        'user': request.user,
        'blog': blog,
        'comments': comments,
    }
    return render(request, 'blog/post.html', context)

#修改博客
@login_required(login_url='user:login')
def edit(request: HttpRequest, post_id: int):
    blog = Blog.objects.get(id=post_id)

    if blog.author != request.user:
        return HttpResponseForbidden('You do not own this post')

    if request.method == 'GET':
        context = {
            'user': request.user,
            'blog': blog
        }
        return render(request, 'blog/edit.html', context)
    elif request.method == 'POST':
        blog.content = request.POST['content']
        blog.save()
        return redirect('blog:blog', post_id)

#评论
@login_required(login_url='user:login')
def comment(request, blog_id):
    if request.method == 'GET':
        return HttpResponseImATeaPot()
    elif request.method == 'POST':
        Comment.objects.create(**{
            'author': request.user,
            'pub_time': datetime.now(),
            'blog': Blog.objects.get(id=blog_id),
            'content': request.POST['content'],
            'reply': request.POST['reply']
        }).save()
        return redirect('blog:blog', blog_id)

#写博客
@login_required(login_url='user:login')
def new(request):
    if request.method == 'GET':
        context = {
            "user": request.user,
        }
        return render(request, 'blog/new.html', context)
    elif request.method == 'POST':
        Blog.objects.create(**{
            'author': request.user,
            'pub_time': datetime.now(),
            'content': request.POST['content']
        }).save()
        return redirect('blog:index')

blog/templates/blog/edit.html
{% extends "base.html" %}
{% load static %}

{% block title %}编辑{% endblock %}

{% block head %}
{% endblock %}

{% block content %}
<div class="mdui-container" style="margin-top: 16px;">
    <div id="editor" style="width: 100%; height: 600px">
    </div>

    <div class="mdui-row">
        <button class="mdui-btn mdui-center" id="submit-button">
            <i class="mdui-icon material-icons">check</i>
            发布
        </button>
    </div>
</div>

<form class="mdui-hidden" method="post" action="{% url 'blog:edit' blog.id %}">
    {% csrf_token %}
    <textarea name="content" id="content-input"></textarea>
</form>

<script>
    let editor;
    $(function () {
        require.config({
            paths: {
                "vs": '{% static "node_modules/monaco-editor/min/vs" %}'
            }
        });
        value = `{{ blog.content | escapejs }}`;
        require(['vs/editor/editor.main'], function () {
            editor = monaco.editor.create(document.getElementById('editor'), {
                value: value,
                autoClosingBrackets: 'never',
                language: 'markdown'
            });
        });
        $('#submit-button').click(e => {
            var content = editor.getValue();
            $('#content-input').val(content);
            $('form').submit();
        });
    });
</script>
<script src="https://unpkg.com/mdui@1.0.2/dist/js/mdui.min.js"></script>
<script src="{% static 'node_modules/monaco-editor/min/vs/loader.js' %}"></script>
{% endblock %}

blog/templates/blog/index.html
{% extends "base.html" %}

{% block title %}博客{% endblock %}

{% load extras %}

{% block head %}
<link rel="stylesheet" href="/static/css/blog.css" />
<style>
    .post-title {
        font-size: 48px;
        font-weight: 200;
    }

    .post-title-link {
        text-decoration: none;
        transition: color .2s linear;
        color: black;
    }

    .post-title-link:hover {
        color: skyblue;
        transition: color .2s linear;
    }

    .post-content {
        font-size: 32px;
        padding-top: 12px;
        font-weight: 300;
    }

	body {
		background: none;
	}
</style>
{% endblock %}

{% block content %}
<body>
<a href="{% url 'blog:new' %}" class="mdui-fab mdui-fab-fixed mdui-ripple mdui-color-pink-200" style="z-index: 1000;">
    <i class="mdui-icon material-icons">add</i>
</a>

<div class="mdui-container">

    {% for blog in blogs %}
    <div class="mdui-row" style="margin-top: 32px;">
        <div class="mdui-text-center mdui-text-truncate post-title">
            <a class="post-title-link" href="{% url 'blog:blog' blog.id %}">
                {{blog.meta.title}}
            </a>
        </div>
    </div>
    <div class="mdui-row">
        <div class="mdui-text-center post-info">
            <i class="mdui-icon material-icons">account_circle</i>
            @{{blog.author.username}} |
            <span title='{{ blog.pub_time|date:"c" }}'>
                <i class="mdui-icon material-icons">today</i>
                {{ blog.pub_time | date:"Y/m/d G:i" }}
            </span>
        </div>
    </div>

    <div class="mdui-row">
        <div class="mdui-col-offset-md-2 mdui-col-md-8 mdui-col-xs-12 mdui-truncate">
            {{blog.formatted | overview | safe}}
        </div>
    </div>

    <div class="mdui-divider mdui-center" style="width: 65%;"></div>
    {% endfor %}

</div>
</body>
{% endblock %}

blog/templates/blog/new.html
{% extends "base.html" %}
{% load static %}

{% block title %}发布博客{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
<style>
	body {
		background: none;
		background-color: rgba(212, 175, 200, 0.051);
	}
</style>
<body>
<div class="mdui-container" style="margin-top: 16px;">
    <div id="editor" style="width: 100%; height: 600px">
    </div>

    <div class="mdui-row">
        <button class="mdui-btn mdui-center" id="submit-button">
            <i class="mdui-icon material-icons">check</i>
            发布
        </button>
    </div>
</div>
<form class="mdui-hidden" method="post" action="{% url 'blog:new' %}">
    {% csrf_token %}
    <input name="title" id="title-input">
    <input name="tags" id="tags-input">
    <textarea name="content" id="content-input"></textarea>
</form>
<script src="https://unpkg.com/mdui@1.0.2/dist/js/mdui.min.js"></script>
<script src="{% static 'node_modules/monaco-editor/min/vs/loader.js' %}"></script>
<script>
    let editor;
    $(function () {
        require.config({
            paths: {
                "vs": '{% static "node_modules/monaco-editor/min/vs" %}'
            }
        });
        value = `{\n\t"title": "",\n\t"tags": []\n}\n---\n\n[[readmore_anchor]]\n`;
        require(['vs/editor/editor.main'], function () {
            editor = monaco.editor.create(document.getElementById('editor'), {
                value: value,
                language: 'markdown'
            });
        });
        $('#submit-button').click(e => {
            var raw = editor.getValue().split('---');
            var metadata = JSON.parse(raw[0]);
            var content = raw[1];
            $('#title-input').val(metadata.title);
            $('#tags-input').val(JSON.stringify(metadata.tags));
            $('#content-input').val(content);
            $('form').submit();
        });
    });
</script>
</body>
{% endblock %}

blog/templates/blog/post.html
{% extends "base.html" %}

{% load static %}

{% block title %}博客详情{% endblock %}


{% block head %}
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
<link rel="stylesheet" href="{% static 'css/blog.css' %}" />
{% endblock %}

{% block content %}


<link rel="stylesheet" href="{% static 'css/codehilite.css' %}" />


{% if editable %}
<a href="{% url 'blog:edit' blog.id %}" class="mdui-fab mdui-fab-fixed mdui-ripple mdui-color-pink-200" style="z-index: 1000;">
    <i class="mdui-icon material-icons">edit</i>
</a>
{% endif %}

<div class="mdui-container" style="padding-top: 32px;">
    <div class="mdui-row">
        <div class="mdui-text-center post-title">
            {{blog.meta.title}}
        </div>
    </div>
    <div class="mdui-row">
        <div class="mdui-text-center post-info">
            <i class="mdui-icon material-icons">account_circle</i>
            @{{blog.author.username}} |
            <span title='{{ post.pub_time|date:"c" }}'>
                <i class="mdui-icon material-icons">today</i>
                {{ blog.pub_time | date:"Y/m/d G:i" }}
            </span>
        </div>
    </div>

    <div class="mdui-row">
        <div class="mdui-col-offset-md-2 mdui-col-md-8 mdui-col-xs-12">
            {{ blog.formatted | safe }}
        </div>
    </div>
</div>

<div class="mdui-container">
    {% comment %} <div class="mdui-row">
        <div class="mdui-col-xs-1 mdui-col-offset-xs-10">
            <button class="mdui-btn mdui-btn-icon btn-toggle-blur mdui-ripple" id="like-button" onclick="like_or_not()">
                <i class="mdui-icon material-icons" id="like-icon">favorite{% if liked == 0 %}_border{% endif %}</i>
            </button>
        </div>
    </div> {% endcomment %}
    {% include "blog/components/comments.html" with comments=comments blog=blog%}
</div>
</body>
{% endblock %}