NoelPlus/urls.py
#NoelPlus-urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('zone.urls')),
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('chat/',include('chat.urls')),
    path('blog/',include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.THUMBNAIL_URL, document_root=settings.THUMBNAIL_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
#blog-urls
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:blog_id>/', views.blog, name='blog'),
    #path('<int:blog_id>/like/', views.ike, name='like'),
    path('<int:post_id>/edit/', view=views.edit, name='edit'),
    path('<int:blog_id>/comment/', view=views.comment, name='comment'),
    path('new/', view=views.new, name='new'),
]

gpt/urls.py
from django.urls import path
from . import views

app_name = 'gpt'

urlpatterns = [
    path('', views.gpt, name='gpt'),
]

noel-refactored/urls.py
#noel-refactored-urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('index.urls')),
    path('zone/',include('zone.urls')),
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('chat/',include('chat.urls')),
    path('blog/',include('blog.urls')),
    path('gpt/',include('gpt.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.THUMBNAIL_URL, document_root=settings.THUMBNAIL_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.my, name='my'),
    path('register/',views.register, name='register'),
    path('login/', views.login_, name='login'),
    path('logout/', views.logout_, name='logout'),
    path('edit/', views.edit, name='edit'),
    path('<int:target_id>/', views.user, name='user'),
    path('<int:target_id>/follow', views.follow, name='follow'),
]

blog/models.py
#blog-models
from django.db import models
from django.conf import settings

class Blog(models.Model):
    content = models.TextField(verbose_name='博文内容')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='作者')
    pub_time = models.DateTimeField('发布日期')
    pinned = models.BooleanField('是否顶置', default=False)

class Like(models.Model):
    post = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name='所属博客')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='点赞者', related_name='博客点赞者')

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name='所属博客')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='评论者', related_name='博客评论者')
    content = models.CharField('评论内容', max_length=1000)
    pub_time = models.DateTimeField('发布时间')
    reply = models.IntegerField('Reply index', default=-1)

blog/views.py
from django import template
from django.shortcuts import render, redirect
from django.http import *
from django.contrib.auth.decorators import login_required
from datetime import datetime
import markdown

from .models import *


class HttpResponseImATeaPot(HttpResponse):
    status_code = 418

def mdconv(text: str):
    md = markdown.Markdown(
        extensions=[
            'markdown.extensions.codehilite',
            'markdown.extensions.meta',
            'markdown.extensions.extra',
            'pymdownx.arithmatex'
        ],
        extension_configs={
            'pymdownx.arithmatex': {
                'generic': True
            }
        }
    )
    res = md.convert(text)
    meta = md.Meta
    for i in meta:
        if len(meta[i]) == 1:
            meta[i] = meta[i][0]
    return (res, md.Meta)


#博客选择页面
@login_required(login_url='user:login')
def index(request):
    blogs = Blog.objects.all().order_by('-pinned','-pub_time')
    if len(blogs) > 30:
        blogs = blogs[:30]
    
    for blog in blogs:
        blog.comment_count = Comment.objects.filter(blog=blog).count()
        blog.formatted, blog.meta = mdconv(blog.content)
    
    context = {
        "user": request.user,
        "blogs": blogs
    }
    return render(request, 'blog/index.html', context)

#博客详情页
@login_required(login_url='user:login')
def blog(request, blog_id):
    blog = Blog.objects.get(id=blog_id) 
    comments = Comment.objects.filter(blog=blog)
    blog.formatted, blog.meta = mdconv(blog.content)
    context = {
        'editable': request.user == blog.author,
        'user': request.user,
        'blog': blog,
        'comments': comments,
    }
    return render(request, 'blog/post.html', context)

#修改博客
@login_required(login_url='user:login')
def edit(request: HttpRequest, post_id: int):
    blog = Blog.objects.get(id=post_id)

    if blog.author != request.user:
        return HttpResponseForbidden('You do not own this post')

    if request.method == 'GET':
        context = {
            'user': request.user,
            'blog': blog
        }
        return render(request, 'blog/edit.html', context)
    elif request.method == 'POST':
        blog.content = request.POST['content']
        blog.save()
        return redirect('blog:blog', post_id)

#评论
@login_required(login_url='user:login')
def comment(request, blog_id):
    if request.method == 'GET':
        return HttpResponseImATeaPot()
    elif request.method == 'POST':
        Comment.objects.create(**{
            'author': request.user,
            'pub_time': datetime.now(),
            'blog': Blog.objects.get(id=blog_id),
            'content': request.POST['content'],
            'reply': request.POST['reply']
        }).save()
        return redirect('blog:blog', blog_id)

#写博客
@login_required(login_url='user:login')
def new(request):
    if request.method == 'GET':
        context = {
            "user": request.user,
        }
        return render(request, 'blog/new.html', context)
    elif request.method == 'POST':
        Blog.objects.create(**{
            'author': request.user,
            'pub_time': datetime.now(),
            'content': request.POST['content']
        }).save()
        return redirect('blog:index')

blog/templates/blog/components/comments.html
<div class="mdui-row mdui-valign" style="margin: 32px 0 32px 0;">
    <div class="mdui-col-md-7 mdui-col-xs-11 mdui-col-offset-md-2">
        <form action="{% url 'blog:comment' blog.id %}" method="post">
            {% csrf_token %}
            <input class="mdui-hidden" id="input-reply" name="reply" value="-1">
            <div class="mdui-textfield">
                <textarea class="mdui-textfield-input" id="input-comment" name="content"
                    placeholder="说点难听的~"></textarea>
            </div>
        </form>
    </div>
    <div calss="mdui-col-xs-1">
        <button class="mdui-btn mdui-center" id="comment-submit">评论</button>
    </div>
</div>

{% for comment in comments %}
<div class="comment" comment-reply="{{comment.reply}}" comment-index="{{forloop.counter}}">
    <div class="mdui-row">
        <div class="mdui-col-offset-md-2 mdui-col-md-1 mdui-col-xs-2">
            <a href="{% url 'user:user' comment.author.id %}">
                <img src="{{ comment.author.avatar.url }}" class="avatar" />
            </a>
        </div>
        <div class="mdui-col-md-7 mdui-col-xs-10 mdui-container">
            <div class="mdui-row">
                <span class="comment-nicnkname mdui-hidden-md-down">{{comment.author.nickname}}</span>
                <span class="comment-username">@{{comment.author.username}}</span>
                <span class="user-title user-title-style-{{comment.author.title_style}}">{{comment.author.title}}</span>
            </div>
            <div class="mdui-row">
                <p class="comment-content">{{comment.content}}</p>
                <span class="comment-pubtime" title='{{comment.pub_time|date:"c"}}'>{{comment.pub_time|date:"Y/m/d G:i"}}</span>
            </div>
        </div>
    </div>
    <div class="reply" style="padding-left: 5%"></div>
</div>
{% endfor %}

<script>
    $('#comment-submit').click(e => {
        if ($('#input-comment').val().trim().length == 0) {
            mdui.snackbar('评论不能为空');
        }
        else {
            $('form').submit();
        }
    });
    $('.comment-content').dblclick(e => {
        var idx = $(e.target).parents('.comment').first().attr('comment-index');
        var rep = $(e.target).parents('.comment').first().find('.comment-username').first().text();
        $('#input-reply').val(idx);
        $('#input-comment').attr('placeholder', `回复 ${rep}...`);
    });
    $(function () {
        $('.comment').filter(x => $(x).attr('comment-reply') != -1).each((i, elem) => {
            $(elem).appendTo(`.comment[comment-index="${$(elem).attr('comment-reply')}"] > .reply`);
        })
    });
</script>