NoelPlus/urls.py
#NoelPlus-urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('zone.urls')),
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('chat/',include('chat.urls')),
    path('blog/',include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.THUMBNAIL_URL, document_root=settings.THUMBNAIL_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gpt/urls.py
from django.urls import path
from . import views

app_name = 'gpt'

urlpatterns = [
    path('', views.gpt, name='gpt'),
]

noel-refactored/urls.py
#noel-refactored-urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('index.urls')),
    path('zone/',include('zone.urls')),
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('chat/',include('chat.urls')),
    path('blog/',include('blog.urls')),
    path('gpt/',include('gpt.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.THUMBNAIL_URL, document_root=settings.THUMBNAIL_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.my, name='my'),
    path('register/',views.register, name='register'),
    path('login/', views.login_, name='login'),
    path('logout/', views.logout_, name='logout'),
    path('edit/', views.edit, name='edit'),
    path('<int:target_id>/', views.user, name='user'),
    path('<int:target_id>/follow', views.follow, name='follow'),
]

user/models.py
#user-models
from typing import Any
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.deconstruct import deconstructible
import os

@deconstructible
class Rename(object):
    def __init__(self, path):
        self.path = path
    def __call__(self, inst, name):
        ext = name.split('.')[-1]
        filename = f'{inst.username}.{ext}'
        return os.path.join(self.path, filename)

class User(AbstractUser):
    nickname = models.CharField('昵称', max_length=10)
    description = models.TextField('个人介绍', max_length=100, blank=True, null=True)
    sign = models.CharField('签名', max_length=25, blank=True, default='', null=True)
    background_image = models.ImageField('背景图片', upload_to=Rename('media/user/userpage_background'), default='/media/user/userpage_background/backimg.jpg')
    avatar = models.ImageField('头像', upload_to=Rename('media/user/avatar'), default='/media/user/avatar/txdefault.jpg')
    title = models.CharField('头衔', max_length=50, default='普通网友')
    title_style = models.CharField('头衔样式', default='normal', max_length=32)
    
class Follow(models.Model):
    up = models.ForeignKey(User, on_delete=models.CASCADE, related_name="博主")
    fan = models.ForeignKey(User, on_delete=models.CASCADE, related_name="粉丝")

user/views.py
#user-view
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.shortcuts import render, HttpResponse, redirect
from .models import *

#注册
def register(request):
    default_avatar = {"avatar": "media/user/avatar/txdefault.jpg",}
    context = {
        "user": default_avatar,
    }
    if request.method == 'GET':
        return render(request, 'user/register.html', context)
    elif request.method == 'POST':
        user = User.objects.create_user(
            username=request.POST['username'], 
            password=request.POST['password'], 
            nickname=request.POST['nickname'],
        )
        user.save()
        return redirect('user:login')

#登陆
def login_(request):
    default_avatar = {"avatar": "media/user/avatar/txdefault.jpg",}
    context = {
        "user": default_avatar,
    }
    if request.method == 'GET':
        return render(request, 'user/login.html', context)
    if request.method == 'POST':
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            
            return redirect('zone:home')
        else:
            return redirect('user:login')

#登出
@login_required(login_url='user:login')
def logout_(request):
    logout(request)
    return redirect('user:login')

#编辑个人信息
@login_required(login_url='user:login')
def edit(request):
    user = User.objects.get(username=request.user.username)
    fans = Follow.objects.filter(up=user)
    context = {
        "user": user,
        "fans_count": fans.count(),
    }
    if request.method == 'POST':
        if request.POST['nickname']:
            user.nickname = request.POST['nickname']
        if request.POST['desc']:
            user.description = request.POST['desc']
        if request.POST['sign']:
            user.sign = request.POST['sign']
        if request.FILES.get('img'):
            user.avatar = request.FILES.get('img')
        if request.FILES.get('backimg'):
            user.background_image = request.FILES.get('backimg')
        user.save()
        return redirect('user:my')
    else:
        return render(request, 'user/edit.html', context)

#个人主页
@login_required(login_url='user:login')
def my(request):
    user = User.objects.get(username=request.user.username)
    fans = Follow.objects.filter(up=user)
    context = {
        "user": user,
        "fans_count": fans.count(),
    }
    return render(request, 'user/my.html', context)

#他人主页
@login_required(login_url='user:login')
def user(request, target_id):
    user = User.objects.get(username=request.user.username)
    target = User.objects.get(id=target_id)
    fans_list = Follow.objects.filter(up=target_id)
    following = any(x.fan == user  for x in fans_list)
    context = {
        "target": target,
        "user": user,
        "following": following,
        "is_me": target_id == user.id,
        "fans_count": fans_list.count(),
    }
    return render(request, 'user/user.html', context)

#关注功能
@login_required(login_url='user:login')
def follow(request, target_id):
    user = User.objects.get(username=request.user.username)
    up = User.objects.get(id=target_id)
    print("我在心里！！！！！！")
    if request.method == 'POST':
        if Follow.objects.filter(up=up, fan=user).count() == 0:
            Follow.objects.create(up=up, fan=user)
            return HttpResponse("关注成功")
        else:
            Follow.objects.filter(up=up, fan=user).delete()
            return HttpResponse("取消关注")
        

user/templates/user/edit.html
{% extends "base.html" %}

{% block title %}编辑资料{% endblock %}

{% block content %}
<style>
	html {
		background-image: url('{{ user.background_image.url }}');
		height: 100%;
		background-position: center;
		background-repeat: no-repeat;
		background-size: cover;
		background-attachment: fixed;
	}

	body {
		background: none;
		margin: 0%;
	}
</style>


<div class="mdui-container profile-view mdui-hoverable" style="opacity: 100%;">
	{% include "user/components/user_info.html" with user=user %}

	{% include "user/components/user_detail.html" with user=user fans_count=fans_count%}


	<div class="mdui-row">
		<div class="mdui-col-xs-6 mdui-col-offset-xs-2 mdui-typo" style="font-size: 24px">
			{{user.description}}
		</div>
	</div>

	<div class="mdui-container">
		<form action="{% url 'user:edit' %}" method="post" enctype="multipart/form-data" class="mdui-center">
			{% csrf_token %}
			<div class="mdui-row mdui-valign">
				<div class="mdui-col-xs-1 mdui-col-offset-xs-2">
					<i class="mdui-icon material-icons">account_circle</i>
				</div>
				<div class="mdui-col-xs-7">
					<div class="mdui-textfield mdui-textfield-floating-label">
						<label class="mdui-textfield-label">昵称</label>
						<input class="mdui-textfield-input" type="text" name="nickname" value="{{user.nickname}}" />
					</div>
				</div>
			</div>

			<div class="mdui-row mdui-valign">
				<div class="mdui-col-xs-1 mdui-col-offset-xs-2">
					<i class="mdui-icon fa-solid fa-austral-sign"></i>
				</div>
				<div class="mdui-col-xs-7">
					<div class="mdui-textfield mdui-textfield-floating-label">
						<label class="mdui-textfield-label">签名</label>
						<input class="mdui-textfield-input" type="text" name="sign" value="{{user.sign}}" />
					</div>
				</div>
			</div>

			<div class="mdui-row mdui-valign">
				<div class="mdui-col-xs-1 mdui-col-offset-xs-2">
					<i class="mdui-icon material-icons">description</i>
				</div>
				<div class="mdui-col-xs-7">
					<div class="mdui-textfield mdui-textfield-floating-label">
						<label class="mdui-textfield-label">简介</label>
						<input class="mdui-textfield-input" type="text" name="desc" value="{{user.description}}" />
					</div>
				</div>
			</div>

			<br />

			<div class="mdui-row mdui-valign">
				<div class="mdui-col-xs-1 mdui-col-offset-xs-2">
					<i class="mdui-icon material-icons">account_circle</i>
				</div>
				<div class="mdui-col-xs-7">
					<div class="">
						<label class="mdui-textfield-label">头像</label>
						<input type="file" name="img" />
					</div>
				</div>
			</div>

			<br />

			<div class="mdui-row mdui-valign">
				<div class="mdui-col-xs-1 mdui-col-offset-xs-2">
					<i class="mdui-icon material-icons">image</i>
				</div>
				<div class="mdui-col-xs-7">
					<div class="">
						<label class="mdui-textfield-label">背景</label>
						<input type="file" name="backimg" />
					</div>
				</div>
			</div>

			<div class="mdui-row">
				<div class="mdui-col-offset-md-10">
					<button class="mdui-btn mdui-ripple">
						<i class="mdui-icon material-icons">save</i>
						保存
					</button>
				</div>
			</div>

		</form>
	</div>

</div>
{% endblock %}

user/templates/user/edit_user.html
{% extends "base.html" %}

{% block title %}编辑资料{% endblock %}

{% block content %}
<style>
	html {
		background-image: url('{{ user.background_image.url }}');
		height: 100%;
		background-position: center;
		background-repeat: no-repeat;
		background-size: cover;
		background-attachment: fixed;
	}

	body {
		background: none;
		margin: 0%;
	}
</style>


<div class="mdui-container profile-view mdui-hoverable" style="opacity: 100%;">
	{% include "user/components/user_info.html" with user=user %}

	{% include "user/components/user_detail.html" with user=user fans_count=fans_count%}


	<div class="mdui-row">
		<div class="mdui-col-xs-6 mdui-col-offset-xs-2 mdui-typo" style="font-size: 24px">
			{{user.description}}
		</div>
	</div>

	<div class="mdui-container">
		<form action="{% url 'user:edit' %}" method="post" enctype="multipart/form-data" class="mdui-center">
			{% csrf_token %}
			<div class="mdui-row mdui-valign">
				<div class="mdui-col-xs-1 mdui-col-offset-xs-2">
					<i class="mdui-icon material-icons">account_circle</i>
				</div>
				<div class="mdui-col-xs-7">
					<div class="mdui-textfield mdui-textfield-floating-label">
						<label class="mdui-textfield-label">昵称</label>
						<input class="mdui-textfield-input" type="text" name="nickname" value="{{user.nickname}}" />
					</div>
				</div>
			</div>

			<div class="mdui-row mdui-valign">
				<div class="mdui-col-xs-1 mdui-col-offset-xs-2">
					<i class="mdui-icon fa-solid fa-austral-sign"></i>
				</div>
				<div class="mdui-col-xs-7">
					<div class="mdui-textfield mdui-textfield-floating-label">
						<label class="mdui-textfield-label">签名</label>
						<input class="mdui-textfield-input" type="text" name="sign" value="{{user.sign}}" />
					</div>
				</div>
			</div>

			<div class="mdui-row mdui-valign">
				<div class="mdui-col-xs-1 mdui-col-offset-xs-2">
					<i class="mdui-icon material-icons">description</i>
				</div>
				<div class="mdui-col-xs-7">
					<div class="mdui-textfield mdui-textfield-floating-label">
						<label class="mdui-textfield-label">简介</label>
						<input class="mdui-textfield-input" type="text" name="desc" value="{{user.description}}" />
					</div>
				</div>
			</div>

			<br />

			<div class="mdui-row mdui-valign">
				<div class="mdui-col-xs-1 mdui-col-offset-xs-2">
					<i class="mdui-icon material-icons">account_circle</i>
				</div>
				<div class="mdui-col-xs-7">
					<div class="">
						<label class="mdui-textfield-label">头像</label>
						<input type="file" name="img" />
					</div>
				</div>
			</div>

			<br />

			<div class="mdui-row mdui-valign">
				<div class="mdui-col-xs-1 mdui-col-offset-xs-2">
					<i class="mdui-icon material-icons">image</i>
				</div>
				<div class="mdui-col-xs-7">
					<div class="">
						<label class="mdui-textfield-label">背景</label>
						<input type="file" name="backimg" />
					</div>
				</div>
			</div>

			<div class="mdui-row">
				<div class="mdui-col-offset-md-10">
					<button class="mdui-btn mdui-ripple">
						<i class="mdui-icon material-icons">save</i>
						保存
					</button>
				</div>
			</div>

		</form>
	</div>

</div>
{% endblock %}

user/templates/user/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}登录{% endblock %}

{% block content %}

<style>
    html {
        background-image: url('{% static "images/loginback.jpg" %}');
        height: 100%;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }

    body {
        background: none;
        margin: 10%;
    }

    .mdui-drawer {
        backdrop-filter: blur(64px) brightness(200%);
    }

    .login-view {
        width: 65%;
        background-color: rgba(255, 255, 255, 0.6);
        backdrop-filter: blur(20px);
        display: block;
        padding: 5%;
    }

    .footer {
        padding: 24px 0 24px 0;
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100%;
        background-color: rgba(255, 255, 255, 0.8);
        transition: background-color .1s linear;
    }

    .footer:hover {
        transition: background-color .1s linear;
        background-color: white;
    }
</style>
<div class="mdui-container login-view">
    <div class="mdui-row">
        <div class="mdui-col-offset-md-3 mdui-col-md-6 mdui-col-offset-xs-1 mdui-col-xs-10">
            <form action="" method="post">
                {% csrf_token %}
                <h2>登录🤫</h2>
                <div class="mdui-textfield mdui-textfield-floating-label">
                    <label class="mdui-textfield-label">用户名</label>
                    <input class="mdui-textfield-input" name="username" id="input-username" pattern="^[\d\w_]+$"
                        required />
                </div>
                <div class="mdui-textfield mdui-textfield-floating-label">
                    <label class="mdui-textfield-label">密码</label>
                    <input class="mdui-textfield-input" name="password" type="password" id="input-password" required />
                </div>
            </form>
        </div>
    </div>

    <div class="mdui-row">
        <div class="mdui-col-xs-12 mdui-col-offset-md-8 mdui-col-md-2 mdui-valign">
            <button class="mdui-btn mdui-ripple" id="button-login">登入</button>
        </div>
    </div>
    <div class="mdui-row" >
        <div class="mdui-col" >
            <p class="mdui-valign"  style="padding-left: 42%;">
                没有账号？<a href="{% url 'user:register' %}">注册</a>
            </p>
        </div>
    </div>
</div>

<div class="mdui-text-center footer">
    <footer>
        ©2023 鲁ICP备2023023515号-1
    </footer>
</div>

<script>
    document.getElementById('button-login').addEventListener('click', e => {
        if (document.getElementById('input-username').value.length == 0) {
            mdui.snackbar('Username missing')
            return
        }
        if (document.getElementById('input-password').value.length == 0) {
            mdui.snackbar('Password missing')
            return
        }
        document.querySelector('form').submit();
    })
</script>
{% endblock %}

user/templates/user/my.html
{% extends "base.html" %}


{% block title %}{{user.username}}的个人主页{% endblock %}

{% block content %}
<style>
    html {
        background-image: url('{{ user.background_image.url }}');
        height: 100%;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
    }

    body {
        background: none;
        margin: 10%;
    }

    .mdui-drawer {
        backdrop-filter: blur(64px) brightness(200%);
        background-color: white;
    }
</style>

<div class="mdui-container profile-view">
    {% include "user/components/user_info.html" with user=user %}
    
    {% include "user/components/user_detail.html" with user=user fans_count=fans_count%}
    

    <br />

    <div class="mdui-row">
        <div class="mdui-col-xs-6 mdui-col-offset-xs-2 mdui-typo" style="font-size: 24px;color:black">
            {{user.description}}
        </div>
    </div>

    <div class="mdui-row">
        <div class="mdui-col-xs-2 mdui-col-offset-md-10">
            <a href="{% url 'user:edit' %}" class="mdui-btn mdui-ripple">编辑信息</a>
        </div>
    </div>
</div>

<script>
    function toggleHidden() {
        document.querySelector('.profile-view').classList.toggle('profile-view-hidden');
    }
</script>

<button class="mdui-btn mdui-fab mdui-fab-fixed mdui-ripple mdui-color-pink-50" onclick="toggleHidden()">
    <i class="mdui-icon material-icons">image</i>
</button>

{% endblock %}

user/templates/user/others_page.html
{% extends "base.html" %}

{% block title %}{{target.username}}的个人主页{% endblock %}

{% block content %}
<style>
    html {
        background-image: url('/media/{{ target.background_image }}');
        height: 100%;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }

    body {
        background: none;
        margin: 10%;
    }

    .mdui-drawer {
        backdrop-filter: blur(64px) brightness(200%);
    }
</style>

<div class="mdui-container profile-view mdui-hoverable">
    {% include "user/components/user_info.html" with user=target %}
    {% include "user/components/user_detail.html" with user=target fans_count=fans_count%}

    <br />

    <div class="mdui-row">
        <div class="mdui-col-xs-6 mdui-col-offset-xs-2 mdui-typo" style="font-size: 24px;color:black">
            {{target.description}}
        </div>
    </div>
    {%if is_me == 0 %}
    <div class="mdui-row">
        <div class="mdui-col-xs-2 mdui-col-offset-md-10">
            <button class="mdui-btn mdui-btn-icon btn-toggle-blur mdui-ripple" id="follow-button"
                onclick="follow_or_not()">
                <i class="mdui-icon material-icons" id="follow-icon">
                    {% if following == 0 %}add{% else %}clear{% endif %}
                </i>
            </button>
        </div>
    </div>
</div>
{% endif %}
<script>
    function toggleHidden() {
        document.querySelector('.profile-view').classList.toggle('profile-view-hidden');
    }
    function follow_or_not() {
        var xhr = new XMLHttpRequest();
        var btn = document.getElementById('follow-button');
        var icon = document.getElementById('follow-icon');
        btn.setAttribute('disabled', 'true');
        xhr.open("POST", "{% url 'user:follow' target.id %}");
        xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        xhr.send();
        if (icon.innerHTML.trim() == 'add') {
            icon.innerHTML = 'clear';
        }
        else {
            icon.innerHTML = 'add';
        }
        xhr.onreadystatechange = function () {
            btn.removeAttribute('disabled');
            if (xhr.readyState == 4 && xhr.status == 200) {
                mdui.snackbar(xhr.responseText);
            }
            else if (xhr.readyState == 4) {
                mdui.snackbar('Failed ' + xhr.status);
            }
        };
    }
</script>

<button class="mdui-btn mdui-fab mdui-fab-fixed mdui-ripple mdui-color-pink-50" onclick="toggleHidden()">
    <i class="mdui-icon material-icons">image</i>
</button>

{% endblock %}

user/templates/user/register.html
{% extends "base.html" %}
{% load static %}
{% block title %}注册{% endblock %}

{% block content %}
<style>
    html {
        background-image: url('{% static "images/loginback.jpg" %}');
        height: 100%;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }

    body {
        background: none;
        margin: 10%;
    }

    .mdui-drawer {
        backdrop-filter: blur(64px) brightness(200%);
    }

    .register-view {
        width: 65%;
        background-color: rgba(255, 255, 255, 0.6);
        backdrop-filter: blur(20px);
        display: block;
        padding: 5%;
    }
</style>


<div class="mdui-container register-view">

    <div class="mdui-row">
        <div class="mdui-col-xs-12 mdui-col-offset-md-3 mdui-col-md-6">
            <form action="" method="post">
                {% csrf_token %}
                <h2>注册😕</h2>

                <div class="mdui-textfield mdui-textfield-floating-label">
                    <label class="mdui-textfield-label">用户名</label>
                    <input class="mdui-textfield-input" name="username" id="input-username" pattern="^[\d\w_]+$"
                        required />
                </div>

                <div class="mdui-textfield mdui-textfield-floating-label">
                    <label class="mdui-textfield-label">昵称</label>
                    <input class="mdui-textfield-input" name="nickname" id="input-nickname" required />
                </div>

                <div class="mdui-textfield mdui-textfield-floating-label">
                    <label class="mdui-textfield-label">密码</label>
                    <input class="mdui-textfield-input" name="password" type="password" id="input-password" required />
                </div>
            </form>
        </div>
    </div>

    <div class="mdui-row">
        <div class="mdui-col-offset-md-8 mdui-col-md-1">
            <button class="mdui-btn mdui-ripple" id="button-register">注册</button>
        </div>
    </div>
</div>

<div style="text-align: center;">
    <footer>
        ©2023 鲁ICP备2023023515号-1
    </footer>
</div>

<script>
    document.getElementById('button-register').addEventListener('click', e => {
        if (document.getElementById('input-username').value.length == 0) {
            mdui.snackbar('Username missing')
            return
        }
        if (document.getElementById('input-nickname').value.length == 0) {
            mdui.snackbar('Nickname missing')
            return
        }
        if (document.getElementById('input-password').value.length == 0) {
            mdui.snackbar('Password missing')
            return
        }
        document.querySelector('form').submit()
    })
</script>

{% endblock %}

user/templates/user/user.html
{% extends "base.html" %}

{% block title %}{{target.username}}的个人主页{% endblock %}

{% block content %}
<style>
    html {
        background-image: url('/media/{{ target.background_image }}');
        height: 100%;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }

    body {
        background: none;
        margin: 10%;
    }

    .mdui-drawer {
        backdrop-filter: blur(64px) brightness(200%);
    }
</style>

<div class="mdui-container profile-view mdui-hoverable">
    {% include "user/components/user_info.html" with user=target %}
    {% include "user/components/user_detail.html" with user=target fans_count=fans_count%}

    <br />

    <div class="mdui-row">
        <div class="mdui-col-xs-6 mdui-col-offset-xs-2 mdui-typo" style="font-size: 24px;color:black">
            {{target.description}}
        </div>
    </div>
    {%if is_me == 0 %}
    <div class="mdui-row">
        <div class="mdui-col-xs-2 mdui-col-offset-md-10">
            <button class="mdui-btn mdui-btn-icon btn-toggle-blur mdui-ripple" id="follow-button"
                onclick="follow_or_not()">
                <i class="mdui-icon material-icons" id="follow-icon">
                    {% if following == 0 %}add{% else %}clear{% endif %}
                </i>
            </button>
        </div>
    </div>
</div>
{% endif %}
<script>
    function toggleHidden() {
        document.querySelector('.profile-view').classList.toggle('profile-view-hidden');
    }
    function follow_or_not() {
        var xhr = new XMLHttpRequest();
        var btn = document.getElementById('follow-button');
        var icon = document.getElementById('follow-icon');
        btn.setAttribute('disabled', 'true');
        xhr.open("POST", "{% url 'user:follow' target.id %}");
        xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        xhr.send();
        if (icon.innerHTML.trim() == 'add') {
            icon.innerHTML = 'clear';
        }
        else {
            icon.innerHTML = 'add';
        }
        xhr.onreadystatechange = function () {
            btn.removeAttribute('disabled');
            if (xhr.readyState == 4 && xhr.status == 200) {
                mdui.snackbar(xhr.responseText);
            }
            else if (xhr.readyState == 4) {
                mdui.snackbar('Failed ' + xhr.status);
            }
        };
    }
</script>

<button class="mdui-btn mdui-fab mdui-fab-fixed mdui-ripple mdui-color-pink-50" onclick="toggleHidden()">
    <i class="mdui-icon material-icons">image</i>
</button>

{% endblock %}

user/templates/user/user_page.html
{% extends "base.html" %}


{% block title %}{{user.username}}的个人主页{% endblock %}

{% block content %}
<style>
    html {
        background-image: url('{{ user.background_image.url }}');
        height: 100%;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
    }

    body {
        background: none;
        margin: 10%;
    }

    .mdui-drawer {
        backdrop-filter: blur(64px) brightness(200%);
        background-color: white;
    }
</style>

<div class="mdui-container profile-view">
    {% include "user/components/user_info.html" with user=user %}
    
    {% include "user/components/user_detail.html" with user=user fans_count=fans_count%}
    

    <br />

    <div class="mdui-row">
        <div class="mdui-col-xs-6 mdui-col-offset-xs-2 mdui-typo" style="font-size: 24px;color:black">
            {{user.description}}
        </div>
    </div>

    <div class="mdui-row">
        <div class="mdui-col-xs-2 mdui-col-offset-md-10">
            <a href="{% url 'user:edit' %}" class="mdui-btn mdui-ripple">编辑信息</a>
        </div>
    </div>
</div>

<script>
    function toggleHidden() {
        document.querySelector('.profile-view').classList.toggle('profile-view-hidden');
    }
</script>

<button class="mdui-btn mdui-fab mdui-fab-fixed mdui-ripple mdui-color-pink-50" onclick="toggleHidden()">
    <i class="mdui-icon material-icons">image</i>
</button>

{% endblock %}