NoelPlus/urls.py
#NoelPlus-urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('zone.urls')),
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('chat/',include('chat.urls')),
    path('blog/',include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.THUMBNAIL_URL, document_root=settings.THUMBNAIL_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
#blog-urls
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:blog_id>/', views.blog, name='blog'),
    #path('<int:blog_id>/like/', views.ike, name='like'),
    path('<int:post_id>/edit/', view=views.edit, name='edit'),
    path('<int:blog_id>/comment/', view=views.comment, name='comment'),
    path('new/', view=views.new, name='new'),
]

chat/urls.py
#chat-url
from django.urls import path
from . import views
app_name = 'chat'
urlpatterns = [
    path('', views.chat, name='chat'),
]

gpt/urls.py
from django.urls import path
from . import views

app_name = 'gpt'

urlpatterns = [
    path('', views.gpt, name='gpt'),
]

noel-refactored/urls.py
#noel-refactored-urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('index.urls')),
    path('zone/',include('zone.urls')),
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('chat/',include('chat.urls')),
    path('blog/',include('blog.urls')),
    path('gpt/',include('gpt.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.THUMBNAIL_URL, document_root=settings.THUMBNAIL_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.my, name='my'),
    path('register/',views.register, name='register'),
    path('login/', views.login_, name='login'),
    path('logout/', views.logout_, name='logout'),
    path('edit/', views.edit, name='edit'),
    path('<int:target_id>/', views.user, name='user'),
    path('<int:target_id>/follow', views.follow, name='follow'),
]

zone/urls.py
#zone-urls
from django.urls import path
from . import views
app_name = 'zone'
urlpatterns = [
    path('', views.home, name='home'),  
    path('edit_post/', views.edit_post, name='edit_post'),
    path('post/<int:post_id>', views.post, name='post'),
    path('post/<int:post_id>/like', views.post_like, name='post_like'),
    path('post/<int:post_id>/comment', views.comment, name='comment'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>Noel</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/user-titles.css' %}" />
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://unpkg.com/mdui@1.0.2/dist/css/mdui.min.css" />
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <script src="{% static 'js/jquery-3.7.0.min.js' %}"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    {% block head %}{% endblock %}
</head>

<body class="mdui-appbar-with-toolbar">

    <!-- Appbar -->
    <header class="mdui-appbar mdui-appbar-fixed">
        <div class="mdui-toolbar mdui-color-pink-50">
            <a href="javascript:;" class="mdui-btn mdui-btn-icon" mdui-drawer="{target: '.mdui-drawer'}">
                <i class="mdui-icon material-icons">menu</i>
            </a>
            <a href="{% url 'zone:home' %}" class="mdui-typo-headline">
                <h1 style="font-weight:400; font-size: 30px; text-align:center">
                    N
                    <img src="{% static 'images/qll.png' %}" style="width:25px;height:25px;">
                    e l
                </h1>
            </a>
            <a class="mdui-typo-title">{% block title %}[Untitled]{% endblock %}</a>
            <div class="mdui-toolbar-spacer"></div>
            <a href="javascript:;" class="mdui-btn mdui-btn-icon" mdui-menu="{target: '#account-menu'}">
                <img src="/media/{{user.avatar}}" class="appbar-avatar" />
            </a>
            <ul class="mdui-menu" id="account-menu">
                <li class="mdui-menu-item">
                    <a href="{% url 'user:my' %}" class="mdui-ripple">
                        <b>{{user.username}}</b>
                    </a>
                </li>
                <li class="mdui-divider"></li>
                <li class="mdui-menu-item">
                    <a href="{% url 'user:login' %}" class="mdui-ripple">登录</a>
                </li>
                <li class="mdui-menu-item">
                    <a href="{% url 'user:register' %}" class="mdui-ripple">注册</a>
                </li>
                <li class="mdui-menu-item">
                    <a href="{% url 'user:logout' %}" class="mdui-ripple">登出</a>
                </li>
            </ul>
        </div>
    </header>

    <!-- Drawer -->
    <div class="mdui-drawer mdui-drawer-close">
        <ul class="mdui-list">
            <a class="mdui-list-item mdui-ripple" href="{% url 'zone:home' %}">
                <i class="mdui-list-item-icon mdui-icon material-icons">home</i>
                <div class="mdui-list-item-content">首页</div>
            </a>
            <a class="mdui-list-item mdui-ripple" href="{% url 'blog:index' %}">
                <i class="mdui-list-item-icon mdui-icon material-icons">whatshot</i>
                <div class="mdui-list-item-content">博客</div>
            </a>
            <a class="mdui-list-item mdui-ripple" href="{% url 'chat:chat' %}">
                <i class="mdui-list-item-icon mdui-icon material-icons">chat</i>
                <div class="mdui-list-item-content">NChat</div>
            </a>
            <a class="mdui-list-item mdui-ripple" href="{% url 'gpt:gpt' %}">
                <i class="mdui-list-item-icon mdui-icon material-icons">forum</i>
                <div class="mdui-list-item-content">ChatGPT</div>
            </a>
        </ul>
    </div>

    {% block content %}{% endblock %}

</body>

<script>
    document.querySelectorAll('.mdui-drawer > ul > a').forEach(function (e) {
        if (document.location.pathname == e.attributes['href'].value) {
            e.classList.toggle('mdui-list-item-active');
        }
    })
</script>

<script src="https://unpkg.com/mdui@1.0.2/dist/js/mdui.min.js"></script>

</html>

templates/error.html
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title></title>
    <script>
        document.querySelector('title').innerText = location.hostname;
    </script>
    <style>
        a {
            color: rgb(88, 88, 88);
        }

        body {
            background: white;
            color: rgb(95, 99, 104);
            word-wrap: break-word;
        }

        html {
            font-size: 125%;
        }
    </style>
    <style>
        .error-code {
            color: rgb(95, 99, 104);
            font-size: .8em;
            margin-top: 12px;
            text-transform: uppercase;
        }

        h1 {
            color: rgb(32, 33, 36);
            font-size: 1.6em;
            font-weight: normal;
            line-height: 1.25em;
            margin-bottom: 16px;
        }

        .icon {
            height: 72px;
            margin: 0 0 40px;
            width: 72px;
        }

        .interstitial-wrapper {
            box-sizing: border-box;
            font-size: 1em;
            line-height: 1.6em;
            margin: 14vh auto 0;
            max-width: 600px;
            width: 100%;
        }

        #main-message>p {
            display: inline;
        }

        @media (max-width: 700px) {
            .interstitial-wrapper {
                padding: 0 10%;
            }
        }

        @media (max-width: 420px) {
            .interstitial-wrapper {
                padding: 0 5%;
            }
        }

        @media (min-width: 421px) and (min-height: 500px) and (max-height: 560px) {
            .interstitial-wrapper {
                margin-top: 10vh;
            }
        }

        @media (min-height: 400px) and (orientation:portrait) {
            .interstitial-wrapper {
                margin-bottom: 145px;
            }
        }

        @media (min-height: 500px) and (max-height: 650px) and (max-width: 414px) and (orientation: portrait) {
            .interstitial-wrapper {
                margin-top: 7vh;
            }
        }

        @media (min-height: 650px) and (max-width: 414px) and (orientation: portrait) {
            .interstitial-wrapper {
                margin-top: 10vh;
            }
        }

        /* Small mobile screens. No fixed nav. */
        @media (max-height: 400px) and (orientation: portrait),
        (max-height: 239px) and (orientation: landscape),
        (max-width: 419px) and (max-height: 399px) {
            .interstitial-wrapper {
                display: flex;
                flex-direction: column;
                margin-bottom: 0;
            }

            #main-content {
                flex: 1 1 auto;
                order: 0;
            }
        }

        html:not([subframe]) #sub-frame-error {
            display: none;
        }

        h1 {
            margin-top: 0;
            word-wrap: break-word;
        }

        h1 span {
            font-weight: 500;
        }

        a {
            text-decoration: none;
        }

        .icon {
            user-select: none;
            display: inline-block;
        }

        .icon-generic {
            content: -webkit-image-set(url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEgAAABIAQMAAABvIyEEAAAABlBMVEUAAABTU1OoaSf/AAAAAXRSTlMAQObYZgAAAENJREFUeF7tzbEJACEQRNGBLeAasBCza2lLEGx0CxFGG9hBMDDxRy/72O9FMnIFapGylsu1fgoBdkXfUHLrQgdfrlJN1BdYBjQQm3UAAAAASUVORK5CYII=) 1x,
                    url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQAQMAAADdiHD7AAAABlBMVEUAAABTU1OoaSf/AAAAAXRSTlMAQObYZgAAAFJJREFUeF7t0cENgDAMQ9FwYgxG6WjpaIzCCAxQxVggFuDiCvlLOeRdHR9yzjncHVoq3npu+wQUrUuJHylSTmBaespJyJQoObUeyxDQb3bEm5Au81c0pSCD8HYAAAAASUVORK5CYII=) 2x);
        }

        #suggestions-list a {
            color: rgb(26, 115, 232);
        }

        #suggestions-list p {
            margin-block-end: 0;
        }

        #suggestions-list ul {
            margin-top: 0;
        }
    </style>
</head>

<body class="neterror" style="font-family: 'Segoe UI',Arial,'Microsoft Yahei',sans-serif; font-size: 75%">
    <div id="main-frame-error" class="interstitial-wrapper">
        <div id="main-content">
            <div class="icon icon-generic"></div>
            <div id="main-message">
                <h1>
                    <span>无法访问此网站</span>
                </h1>
                <p>
                    <strong>
                        <script>
                            document.write(location.hostname);
                        </script>
                    </strong> {% if hit %}拒绝冲泡咖啡，因为其是茶壶{% else %}意外终止了连接。{% endif %}
                </p>
                <div id="error-information-popup-container">
                    <div id="error-information-popup">
                        <div id="error-information-popup-box">
                            <div id="error-information-popup-content">
                                <div id="suggestions-list">
                                    <p>请试试以下办法：</p>
                                    <ul class="">
                                        <li>{% if hit %}将内容物换为茶叶{% else %}检查网络连接{% endif %}</li>
                                        <li>
                                            <a href="😝">{% if hit %}购置一把咖啡壶{% else %}检查代理服务器和防火墙{% endif %}</a>
                                        </li>
                                        <li>
                                            <a href="😝">{% if hit %}购置一些茶叶{% else %}运行 Windows 网络诊断{% endif %}</a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="error-code">
                                    {% if hit %}ERR_IM_A_TEAPOT{% else %}ERR_CONNECTION_CLOSED{% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

templates/index.html
<head>
    <link rel="stylesheet" href="https://unpkg.com/mdui@1.0.2/dist/css/mdui.min.css" />
    <title>IndexPage</title>
</head>



</script>

<script src="https://unpkg.com/mdui@1.0.2/dist/js/mdui.min.js"></script>

</html>